return {
  alarm_1 = {
    date_dow_bcd = 8,
    enabled = true,
    hour_bcd = 7,
    ignore_date_dow = false,
    ignore_hour = false,
    ignore_minute = false,
    ignore_second = false,
    is_12h_format = true,
    is_date_not_dow = true,
    is_pm = false,
    minute_bcd = 6,
    occurred = false,
    second_bcd = 5,
  },
  alarm_2 = {
    date_dow_bcd = 17,
    enabled = false,
    hour_bcd = 16,
    ignore_date_dow = false,
    ignore_hour = false,
    ignore_minute = false,
    is_12h_format = false,
    is_date_not_dow = false,
    minute_bcd = 9,
    occurred = false,
  },
  at_battery = {
    allow_wave_output = true,
    clock_was_stopped = false,
    stop_clock = false,
  },
  clock_speed = 25,
  enable_wave_32k = true,
  get_temperature = false,
  is_busy = false,
  moment = {
    date_bcd = 34,
    dow_bcd = 3,
    hour_bcd = 22,
    is_12h_format = false,
    is_next_century = false,
    minute_bcd = 37,
    month_bcd = 1,
    second_bcd = 70,
    year_bcd = 32,
  },
  output_alarms_not_wave = false,
  temperature = 23.25,
  wave_freq = 1024,
}