return {
  alarm = {
    {
      date_dow = 8,
      enabled = true,
      hour = 7,
      ignore_date_dow = false,
      ignore_hour = false,
      ignore_minute = false,
      ignore_second = false,
      is_12h_format = true,
      is_date_not_dow = true,
      minute = 6,
      occurred = false,
      second = 5,
    },
    {
      date_dow = 11,
      enabled = true,
      hour = 10,
      ignore_date_dow = true,
      ignore_hour = true,
      ignore_minute = true,
      is_12h_format = false,
      is_date_not_dow = true,
      minute = 9,
      occurred = false,
    },
  },
  at_battery = {
    allow_wave_output = true,
    clock_was_stopped = false,
    stop_clock = false,
  },
  clock_speed = 25,
  enable_wave_32k = true,
  get_temperature = false,
  is_busy = false,
  moment = {
    date = 22,
    dow = 3,
    hour = 16,
    is_12h_format = false,
    minute = 25,
    month = 1,
    second = 46,
    year = 2020,
  },
  output_alarms_not_wave = false,
  temperature = 26.25,
  wave_freq = 1024,
}